### ISSUE TITLE
数据库

### ISSUE THREAD

**Issue by Mercurio-mike** [linran-y/softwarereliabilityaend#1]

**Comment by Mercurio-mike** [comment]
谢谢大佬，已经成功运行了，摸索了半天也会用了
还想问一下大佬，那个Duane模型是还没完全实现吗

**Comment by linran-y** [comment]
> 谢谢大佬，已经成功运行了，摸索了半天也会用了
> 还想问一下大佬，那个Duane模型是还没完全实现吗

时间有点久远了，是南航学生么，是加1677435221，我找找文档发你
